image:
  - ubuntu1804
  - Visual Studio 2019

platform:
  - x64
configuration: 
  - Debug

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
    build_script:
      - cmd: mkdir Build
      - cmd: cd Build
      - cmd: cmake --version
      - cmd: cmake -G "Visual Studio 16 2019" ..
      - cmd: cmake --build ./ --config Debug
  -
    matrix:
      only:
        - image: ubuntu1804
    install:
      - sudo apt-get update -qq && sudo apt-get install -qq
      - sudo apt-get -y install mesa-common-dev libglu1-mesa-dev libgl1-mesa-dev libx11-dev libxcursor-dev 
      - sudo apt-get -y install libxrandr-dev libxi-dev uuid-dev libglfw3 libglfw3-dev gcc-9 g++-9
      - CC=gcc-9 CXX=g++-9
    build_script:
      - cmd: mkdir Build
      - cmd: cd Build
      - cmd: cmake --version
      - cmd: cmake -G "Unix Makefiles" .. -D CMAKE_C_COMPILER=gcc-9 -D CMAKE_CXX_COMPILER=g++-9 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - cmd: cmake --build ./ --config Debug
