image:
  - Ubuntu
  - Visual Studio 2019

platform:
  - x64
configuration: 
  - Debug

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
    build_script:
      - cmd: mkdir Build
      - cmd: cd Build
      - cmd: cmake --version
      - cmd: cmake -G "Visual Studio 16 2019" ..
      - cmd: cmake --build ./ --config Debug
