# codacy configuration file

---

exclude_paths: [
  'Source/Framework/Utility/ThirdParty/**',
  'Documentation/**',
  'Dependencies/**',
  '**/ImGui/**',
  '**/GL/**',
  '**/dirent.h',
  '**/TeImGuiFileBrowser.cpp',
  '**.sh',
  '**.md'
]
