name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install libgl1-mesa-dev
      run: sudo apt-get install libgl1-mesa-dev
      
    - name: Install mesa-common-dev
      run: sudo apt-get install libx11-dev
    
    - name: Install mesa-common-dev
      run: sudo apt-get install libx11-dev
    
    - name: Install libxcursor-dev 
      run: sudo apt-get install libxcursor-dev

    - name: Install libxrandr-dev
      run: sudo apt-get install libxrandr-dev
      
    - name: Install libxi-dev
      run: sudo apt-get install libxi-dev
      
    - name: Install uuid-dev
      run: sudo apt-get install uuid-dev
      
    - name: Install libglfw3
      run: sudo apt-get install libglfw3
      
    - name: Install libglfw3-dev
      run: sudo apt-get install libglfw3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
